### ISSUE TITLE
Some suggestions for improving this model

### ISSUE THREAD

**Issue by YangTakeshi** [IIEdm/TaNP#1]
By replacing the model with a two-layer fully connected layer, you will find that the model achieves a much better performance, and it is recommended to submit the paper to next year's IJCAI.

**Comment by IIEdm** [comment]
LOL～you can have a try and good luck. On 04/20/2021 11:10, 杨康 wrote: 
By replacing the model with a two-layer fully connected layer, you will find that the model achieves a much better performance, and it is recommended to submit the paper to next year's IJCAI.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/IIEdm/TaNP/issues/1",
"url": "https://github.com/IIEdm/TaNP/issues/1",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by IIEdm** [comment]
This a malicious comment of our work without any real empirical results, so I closed this issue.
