### ISSUE TITLE
2 question for TaNP

### ISSUE THREAD

**Issue by a370865882** [IIEdm/TaNP#2]

**Comment by a370865882** [comment]
1. support set and query set in paper are defined in Definition3.1, but I find in [TaNP.py](https://github.com/IIEdm/TaNP/blob/main/TaNP/TaNP.py) line 128 and line 145 during training the support and query set are overlapped.
2. This paper argued cold start users had 10/15/20 interacted items, is it too large? BTW, following the MeLU,MAMO methods, item-consumption length is between 13 and 100, but this paper's length is between 40 and 200. I am curious about the motivation of this setting.

**Comment by dtjayaaa12345** [comment]
Hi, for question 1, one of advantage of neural processes is to represent a distribution over functions, and we have to introduce a training step in our model to reflect this property. So we adopt a random function in data generation. It's ok, since it is not involved with the test phase. For question 2, we do not follow MeLU and MAMO. Because we suppose that a small size of support set can better fit with the setting in meta-learning. Both MeLU and MAMO give more data samples in support set.
